# This file is included only via recursive $(MAKE) invocations from the
# DEFERRED_MK mechanism: each per-stem .mk file (generated by
# GENERATE_DEFERRED_MK_PHASE) loads it with -f Rules.mk -f <stem>.mk to
# run cp-deferred-asset, gzip-asset, and clean-asset for that stem's assets.
# It is not included by the top-level Makefile.
.SECONDEXPANSION:
.PRECIOUS: $(__SRC__)/%/
$(__SRC__)/%/:
	mkdir -p $@

.PHONY: cp-deferred-asset gzip-asset clean-asset
cp-deferred-asset :
gzip-asset :
clean-asset ::