# This file is included only via recursive $(MAKE) invocations from the
# DEFERRED_MK mechanism: each per-stem .mk file (generated by
# GENERATE_DEFERRED_MK_PHASE) loads it with -f Rules.mk -f <stem>.mk to
# run assets-copy, assets-compress, and assets-clean for that stem's assets.
# It is not included by the top-level Makefile.
.SECONDEXPANSION:
.PRECIOUS: $(SRC)/%/
$(SRC)/%/:
	mkdir -p $@

.PHONY: assets-copy assets-compress assets-clean
assets-copy :
assets-compress :
assets-clean ::